//
// Protocol buffers definition for Dadkvs Paxos Service
//
syntax = "proto3";
package dadkvs;

message MultiPaxosPhaseOneRequest {
  repeated PhaseOneRequest request = 1;
}

message MultiPaxosPhaseOneResponse {
  repeated PhaseOneReply response = 1;
}

message MultiPaxosPhaseTwoRequest {
  repeated PhaseTwoRequest request = 1;
}

message MultiPaxosPhaseTwoResponse {
  repeated PhaseTwoReply response = 1;
}

message PhaseOneRequest {
  int32 phase1config    = 1;
  int32 phase1index     = 2;
  int32 phase1timestamp = 3;
}

message PhaseOneReply {
  int32 phase1config    = 1;
  int32 phase1index     = 2;
  bool  phase1accepted  = 3;
  int32 phase1value     = 4;
  int32 phase1timestamp = 5;
}

message PhaseTwoRequest {
  int32 phase2config    = 1;
  int32 phase2index     = 2;
  int32 phase2value     = 3;
  int32 phase2timestamp = 4;
}

message PhaseTwoReply {
  int32 phase2config   = 1;
  int32 phase2index    = 2;
  bool  phase2accepted = 3;
  int32 phase2timestamp = 4;
}

message LearnRequest {
  int32 learnconfig    = 1;
  int32 learnindex     = 2;
  int32 learnvalue     = 3;
  int32 learntimestamp = 4;
}

message LearnReply {
  int32 learnconfig   = 1;
  int32 learnindex    = 2;
  bool  learnaccepted = 3;
}

service DadkvsPaxosService {
  rpc phaseone (MultiPaxosPhaseOneRequest) returns (MultiPaxosPhaseOneResponse);
  rpc phasetwo (MultiPaxosPhaseTwoRequest) returns (MultiPaxosPhaseTwoResponse);
  rpc learn (LearnRequest) returns (LearnReply);
}






