package dadkvs.server;

/* these imported classes are generated by the contract */

import dadkvs.DadkvsConsole;
import dadkvs.DadkvsConsoleServiceGrpc;
import io.grpc.stub.StreamObserver;

import java.util.Arrays;

public class DadkvsConsoleServiceImpl extends DadkvsConsoleServiceGrpc.DadkvsConsoleServiceImplBase {


    DadkvsServerState server_state;

    DebugHandler debugHandler;

    public DadkvsConsoleServiceImpl(DadkvsServerState state, DebugHandler debugHandler) {
        this.server_state = state;
        this.debugHandler = debugHandler;
    }

    @Override
    public void setleader(DadkvsConsole.SetLeaderRequest request, StreamObserver<DadkvsConsole.SetLeaderReply> responseObserver) {
        // for debug purposes
        System.out.println(request);
        // Checking if the server can become a leader according to the current configuration
        int currentConfig = this.server_state.store.read(KeyValueStore.CONFIG_KEY).getValue();
        int[] configMembers = this.server_state.configuration_matrix[currentConfig];
        boolean canBeLeader = server_state.isPartOfConfig(server_state.my_id, configMembers);
        if(!request.getIsleader() || canBeLeader)
            this.server_state.signalNewLeader(request.getIsleader());

        // for debug purposes
        System.out.println("I am the leader = " + this.server_state.i_am_leader);

        //this.server_state.main_loop.wakeup();

        DadkvsConsole.SetLeaderReply response = DadkvsConsole.SetLeaderReply.newBuilder()
                .setIsleaderack(canBeLeader).build();

        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

    @Override
    public synchronized void setdebug(DadkvsConsole.SetDebugRequest request, StreamObserver<DadkvsConsole.SetDebugReply> responseObserver) {
        // for debug purposes
        System.out.println(request);

        boolean response_value = true;

        if (request.getMode() == 1)
            System.exit(-1);
        else if (server_state.debug_mode == 2 && request.getMode() != 2) {
            debugHandler.wakeUpFrozenRequests();
        }
        this.server_state.debug_mode = request.getMode();
        System.out.println("Setting debug mode to = " + this.server_state.debug_mode);

        // Respond to the client
        DadkvsConsole.SetDebugReply response = DadkvsConsole.SetDebugReply.newBuilder()
                .setAck(response_value).build();

        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }
}
